/**
 * Created by tomihei on 17/02/11.
 */

//app action
export const AUTH_REQUEST = "AUTH_REQUEST";
export const AUTH_RESULT = "AUTH_RESULT";
export const AUTH_FAILED = "AUTH_FAILED";
export const TOKEN_NOTFOUND = "TOKEN_NOTFOUND";
export const LOGOUT = "LOGOUT";
export const SUCCESS_LOGOUT = "SUCCESS_LOGOUT";
export const SUCCESS_LOGIN = "SUCCESS_LOGIN";

// login action
export const CHANGE_NAME = 'CHANGE_NAME';
export const CHANGE_EMAIL = 'CHANGE_EMAIL';
export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';
export const LOGIN_INFO_REQUEST = 'LOGIN_INFO_REQUEST';
export const LOGIN_INFO_RESULT = 'LOGIN_INFO_RESULT';
export const CREATE_USER = 'CREATE_USER';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const CHANGE_USERID = 'CHANGE_USERID';


//bookmark

export const CBT = 'CHANGE_BOOKMARK_TITLE';
export const CBD = 'CHANGE_BOOKMARK_DESCRIPTION';
export const CBRE = 'CREATE_BOOKMARK_REQUEST';
export const CBRS = 'CREATE_BOOKMARK_RESULT';
export const CBF = 'CREATE_BOOKMARK_FAILD';

export const BIRE = 'BOOKMARK_INFO_REQUEST';
export const BIRS = 'BOOKMARK_INFO_RESULT';
export const BIRF = 'BOOKMARK_INFO_REQUEST_FAILD';
export const BTIE = 'BOOKMARK_TRIP_INFO_EXCHANGE';
export const BTIR = 'BOOKMARK_TRIP_INFO_REQUEST';
export const TRIP_INFO_RESULT = 'TRIP_INFO_ADD';

export const TRIP_IMAGE_UPDATE_REQUEST = 'TRIP_IMAGE_UPDATE_REQUEST';
export const TRIP_IMAGE_UPDATE_RESULT = 'TRIP_IMAGE_UPDATE_RESULT';
export const TRIP_IMAGE_UPDATE_FAILED = 'TRIP_IMAGE_UPDATE_FAILED';

export const TRIP_INFO_DELETE_REQUEST = 'TRIP_INFO_DELETE_REQUEST';
export const TRIP_INFO_DELETE_RESULT = 'TRIP_INFO_DELETE_RESULT';
export const TRIP_INFO_DELETE_FAILED = 'TRIP_INFO_DELETE_FAILED';
export const CHANGE_TRIP_INFO = 'CHANGE_TRIP_INFO';
export const TRIP_DELETE_DIALOG_OPEN = 'TRIP_DELETE_DIALOG_OPEN';
export const TRIP_DELETE_DIALOG_CLOSE = 'TRIP_DELETE_DIALOG_CLOSE';

export const TRIP_INFO_EDIT_REQUEST = 'TRIP_INFO_EDIT_REQUEST';
export const TRIP_INFO_EDIT_RESULT = 'TRIP_INFO_EDIT_RESULT';
export const TRIP_INFO_EDIT_FAILED = 'TRIP_INFO_EDIT_FAILED';
export const TRIP_EDIT_DIALOG_OPEN = 'TRIP_EDIT_DIALOG_OPEN';
export const TRIP_EDIT_DIALOG_CLOSE = 'TRIP_EDIT_DIALOG_CLOSE';

export const TRIP_OPEN_DIALOG = 'TRIP_OPEN_DIALOG';
export const TRIP_CLOSE_DIALOG = 'TRIP_CLOSE_DIALOG';
export const ADD_TRIP_INFO_REQUEST = 'ADD_TRIP_INFO_REQUEST';
export const ADD_TRIP_INFO_RESULT = 'ADD_TRIP_INFO_RESULT';
export const ADD_TRIP_INFO_FAILD = 'ADD_TRIP_INFO_FAILD';
export const CHANGE_SITE_NAME = 'CHANGE_SITE_NAME';
export const CHANGE_TRIP_INFO_DESC  = 'CHANGE_TRIP_INFO_DESC';
export const CHANGE_LAT = 'CHANGE_LAT';
export const CHANGE_LNG = 'CHANGE_LNG';

export const ADD_PREMISSION_DIALOG_OPEN = 'ADD_PERMISSION_DIALOG_OPEN';
export const ADD_PERMISSION_DIALOG_CLOSE = 'ADD_PERMISSION_DIALOG_CLOSE';
export const ADD_PREMISSION_REQUEST = "ADD_PREMISSION_REQUEST";
export const ADD_PERMISSION_RESULT = "ADD_PERMISSION_RESULT";
export const ADD_PERMISSION_FAILED = "ADD_PERMISSION_FAILED";
export const CHANGE_USER_NAME = "CHANGE_USER_NAME";

export const DEL_PERMISSION_DIALOG_OPEN = 'DEL_PERMISSION_DIALOG_OPEN';
export const DEL_PERMISSION_DIALOG_CLOSE = 'DEL_PERMISSION_DIALOG_CLOSE';
export const DEL_PERMISSION_REQUEST = 'DEL_PERMISSION_REQUEST';
export const DEL_PERMISSION_RESULT = 'DEL_PERMISSION_RESULT';
export const DEL_PERMISSION_FAILED = 'DEL_PERMISSION_FAILED';


//userPage
export const USER_PAGE_AUTH_REQUEST = 'USER_PAGE_AUTH_REQUESST';
export const USER_PAGE_AUTH_RESULT = 'USER_PAGE_AUTH_RESULT';
export const USER_PAGE_BOARD_REQUEST = 'USER_PAGE_BOARD_REQUEST';
export const USER_PAGE_BOARD_RESULT = 'USER_PAGE_BOARD_RESULT';
export const USER_PAGE_BOARD_LAST_PAGE = 'USER_PAGE_BOARD_LAST_PAGE';

//bookmark
export const BOOKMARK_LIST_REQUEST = 'BOOKMARK_LIST_REQUEST';
export const BOOKMARK_LIST_RESULT = 'BOOKMARK_LIST_RESULT';
export const BOOKMARK_LIST_LAST_PAGE ='BOOKMARK_LIST_LAST_PAGE';
export const BOOKMARK_LIST_INIT = 'BOOKMARK_LIST_INIT';

// addVideo SnacBar
export const SNACBAR_OPEN = "SNACBAR_OPEN";
export const SNACBAR_CLOSE = "SNACBAR_CLOSE";


//delete data

export const DELETE_DATA_OPEN = "DELETE_DATA_OPEN";
export const DELETE_DATA_CLOSE = "DELETE_DATA_CLOSE";
export const DELETE_DATA_REQUEST = "DELETE_DATA_REQUEST";
export const DELETE_DATA_RESULT = "DELETE_DATA_RESULT";
export const DELETE_DATA_FAILED = "DELETE_DATA_FAILED";

//comment post
export const INIT_COMMENT_LIST = "INIT_COMMENT_LIST";
export const CHANGE_COMMENT = "CHANGE_COMMENT";
export const COMMENT_POST_REQUEST = "COMMENT_POST_REQUEST";
export const COMMENT_POST_RESULT = "COMMNET_POST_RESULT";
export const COMMENT_POST_FAILED = "COMMNET_POST_FAILED";
export const COMMENT_LIST_REQUEST = "COMMENT_LIST_REQUEST";
export const COMMENT_LIST_RESULT = "COMMENT_LIST_RESULT";
export const COMMENT_LIST_FAILED = "COMMENT_LIST_FAILED";
export const COMMENT_LIST_LAST_PAGE = "COMMENT_LIST_LAST_PAGE";
export const RES_COMMENT_OPEN = "RES_COMENT_OPEN";
export const RES_COMMENT_CLOSE = "RES_COMMENT_CLOSE";


//follow
export const ISFOLLOW_BOARD_REQUEST = "ISFOLLOW_BOARD_REQUEST";
export const ISFOLLOW_BOARD_RESULT = "ISFOLLOW_BOARD_RESULT";
export const ISFOLLOW_USER_REQUEST = "ISFOLLOW_USER_REQUEST";
export const ISFOLLOW_USER_RESULT = "ISFOLLOW_USER_RESULT";
export const FOLLOW_REQUEST = "FOLLOW_REQUEST";
export const DEFOLLOW_REQUEST= "DEFOLLOW_REQUEST";
export const DEFOLLOW_USER_REQUEST = "DEFOLLOW_USER_REQUEST";
export const FOLLOW_RESULT = "FOLLOW_RESULT";
export const DEFOLLOW_RESULT = "DEFOLLOW_RESULT";
export const DEFOLLOW_USER_RESULT = "DEFOLLOW_USER_RESULT";
export const FOLLOW_REQUEST_FAILED = "FOLLOW_REQUEST_FAILED";

//follow_info
export const INIT_FOLLOW_LIST = "INIT_FOLLOW_LIST";
export const FOLLOW_LIST_REQUEST = "FOLLOW_LIST_REQUEST";
export const FOLLOW_LIST_RESULT = "FOLLOW_LIST_RESULT";
export const FOLLOW_LIST_LAST_PAGE = "FOLLOW_LIST_LAST_PAGE";
export const FOLLOW_LIST_REQUEST_FAILED = "FOLLOW_LIST_REQUEST_FAILED";
export const FOLLOW_LIST_OPEN = "FOLLOW_LIST_OPEN";
export const FOLlOW_LIST_CLOSE = "FOLLOW_LIST_CLOSE";

//follower followee

export const INIT_FOLLOWER_LIST = "INIT_FOLLOWER_LIST";
export const FOLLOWER_LIST_REQUEST = "FOLLOWER_LIST_REQUEST";
export const FOLLOWER_LIST_RESULT = "FOLLOWER_LIST_RESULT";
export const FOLLOWER_LIST_LAST_PAGE = "FOLLOWER_LIST_LAST_PAGE";
export const FOLLOWER_LIST_OPEN = "FOLLOWER_LIST_OPEN";
export const FOLLOWER_LIST_CLOSE = "FOLLOWER_LIST_CLOSE";

export const INIT_FOLLOWEE_LIST = "INIT_FOLLOWEE_LIST";
export const FOLLOWEE_LIST_REQUEST = "FOLLOWEE_LIST_REQUEST";
export const FOLLOWEE_LIST_RESULT = "FOLLOWEE_LIST_RESULT";
export const FOLLOWEE_LIST_LAST_PAGE = "FOLLOWEE_LIST_LAST_PAGE";
export const FOLLOWEE_LIST_OPEN = "FOLLOWEE_LIST_OPEN";
export const FOLLOWEE_LIST_CLOSE = "FOLLOWEE_LIST_CLOSE";

//search

export const INIT_SEARCH_LIST = "INIT_SEARCH_LIST";
export const SEARCH_LIST_REQUEST = "SEARCH_LIST_REQUEST";
export const SEARCH_LIST_RESULT = "SEARCH_LIST_RESULT";
export const SEARCH_LIST_LAST_PAGE = "SEARCH_LIST_LAST_PAGE";
export const CHANGE_WORD = "CHANGE_WORD";


//Animation
export const MENU_FIXED = "MENU_FIXED";
export const INIT_MENU_FIXED = "INIT_MENU_FIXED";
